#   Copyright 2022 Stroke Research at Vall d'Hebron Research Institute (VHIR), Barcelona, Spain.

from paraview.simple import *

def set_default_display_properties(segmentation_vtk_display):
    # Set defaults for the display properties.
    segmentation_vtk_display.Selection = None
    segmentation_vtk_display.Representation = 'Surface'
    segmentation_vtk_display.ColorArrayName = [None, '']
    segmentation_vtk_display.LookupTable = None
    segmentation_vtk_display.MapScalars = 1
    segmentation_vtk_display.MultiComponentsMapping = 0
    segmentation_vtk_display.InterpolateScalarsBeforeMapping = 1
    segmentation_vtk_display.Opacity = 1.0
    segmentation_vtk_display.PointSize = 2.0
    segmentation_vtk_display.LineWidth = 1.0
    segmentation_vtk_display.RenderLinesAsTubes = 0
    segmentation_vtk_display.RenderPointsAsSpheres = 0
    segmentation_vtk_display.Interpolation = 'Gouraud'
    segmentation_vtk_display.Specular = 0.0
    segmentation_vtk_display.SpecularColor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.SpecularPower = 100.0
    segmentation_vtk_display.Luminosity = 0.0
    segmentation_vtk_display.Ambient = 0.0
    segmentation_vtk_display.Diffuse = 1.0
    segmentation_vtk_display.Roughness = 0.3
    segmentation_vtk_display.Metallic = 0.0
    segmentation_vtk_display.EdgeTint = [1.0, 1.0, 1.0]
    segmentation_vtk_display.Anisotropy = 0.0
    segmentation_vtk_display.AnisotropyRotation = 0.0
    segmentation_vtk_display.BaseIOR = 1.5
    segmentation_vtk_display.CoatStrength = 0.0
    segmentation_vtk_display.CoatIOR = 2.0
    segmentation_vtk_display.CoatRoughness = 0.0
    segmentation_vtk_display.CoatColor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.SelectTCoordArray = 'None'
    segmentation_vtk_display.SelectNormalArray = 'Normals'
    segmentation_vtk_display.SelectTangentArray = 'None'
    segmentation_vtk_display.Texture = None
    segmentation_vtk_display.RepeatTextures = 1
    segmentation_vtk_display.InterpolateTextures = 0
    segmentation_vtk_display.SeamlessU = 0
    segmentation_vtk_display.SeamlessV = 0
    segmentation_vtk_display.UseMipmapTextures = 0
    segmentation_vtk_display.ShowTexturesOnBackface = 1
    segmentation_vtk_display.BaseColorTexture = None
    segmentation_vtk_display.NormalTexture = None
    segmentation_vtk_display.NormalScale = 1.0
    segmentation_vtk_display.CoatNormalTexture = None
    segmentation_vtk_display.CoatNormalScale = 1.0
    segmentation_vtk_display.MaterialTexture = None
    segmentation_vtk_display.OcclusionStrength = 1.0
    segmentation_vtk_display.AnisotropyTexture = None
    segmentation_vtk_display.EmissiveTexture = None
    segmentation_vtk_display.EmissiveFactor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.FlipTextures = 0
    segmentation_vtk_display.BackfaceRepresentation = 'Follow Frontface'
    segmentation_vtk_display.BackfaceAmbientColor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.BackfaceOpacity = 1.0
    segmentation_vtk_display.Position = [0.0, 0.0, 0.0]
    segmentation_vtk_display.Scale = [1.0, 1.0, 1.0]
    segmentation_vtk_display.Orientation = [0.0, 0.0, 0.0]
    segmentation_vtk_display.Origin = [0.0, 0.0, 0.0]
    segmentation_vtk_display.CoordinateShiftScaleMethod = 'Always Auto Shift Scale'
    segmentation_vtk_display.Pickable = 1
    segmentation_vtk_display.Triangulate = 0
    segmentation_vtk_display.UseShaderReplacements = 0
    segmentation_vtk_display.ShaderReplacements = ''
    segmentation_vtk_display.NonlinearSubdivisionLevel = 1
    segmentation_vtk_display.UseDataPartitions = 0
    segmentation_vtk_display.OSPRayUseScaleArray = 'All Approximate'
    segmentation_vtk_display.OSPRayScaleArray = 'Normals'
    segmentation_vtk_display.OSPRayScaleFunction = 'PiecewiseFunction'
    segmentation_vtk_display.OSPRayMaterial = 'None'
    segmentation_vtk_display.BlockSelectors = ['/']
    segmentation_vtk_display.BlockColors = []
    segmentation_vtk_display.BlockOpacities = []
    segmentation_vtk_display.Orient = 0
    segmentation_vtk_display.OrientationMode = 'Direction'
    segmentation_vtk_display.SelectOrientationVectors = 'None'
    segmentation_vtk_display.Scaling = 0
    segmentation_vtk_display.ScaleMode = 'No Data Scaling Off'
    segmentation_vtk_display.ScaleFactor = 26.744259643554688
    segmentation_vtk_display.SelectScaleArray = 'None'
    segmentation_vtk_display.GlyphType = 'Arrow'
    segmentation_vtk_display.UseGlyphTable = 0
    segmentation_vtk_display.GlyphTableIndexArray = 'None'
    segmentation_vtk_display.UseCompositeGlyphTable = 0
    segmentation_vtk_display.UseGlyphCullingAndLOD = 0
    segmentation_vtk_display.LODValues = []
    segmentation_vtk_display.ColorByLODIndex = 0
    segmentation_vtk_display.GaussianRadius = 1.3372129821777343
    segmentation_vtk_display.ShaderPreset = 'Sphere'
    segmentation_vtk_display.CustomTriangleScale = 3
    segmentation_vtk_display.CustomShader = """ // This custom shader code define a gaussian blur
    // Please take a look into vtkSMPointGaussianRepresentation.cxx
    // for other custom shader examples
    //VTK::Color::Impl
    float dist2 = dot(offsetVCVSOutput.xy,offsetVCVSOutput.xy);
    float gaussian = exp(-0.5*dist2);
    opacity = opacity*gaussian;
    """
    segmentation_vtk_display.Emissive = 0
    segmentation_vtk_display.ScaleByArray = 0
    segmentation_vtk_display.SetScaleArray = ['POINTS', 'Normals']
    segmentation_vtk_display.ScaleArrayComponent = 'X'
    segmentation_vtk_display.UseScaleFunction = 1
    segmentation_vtk_display.ScaleTransferFunction = 'PiecewiseFunction'
    segmentation_vtk_display.OpacityByArray = 0
    segmentation_vtk_display.OpacityArray = ['POINTS', 'Normals']
    segmentation_vtk_display.OpacityArrayComponent = 'X'
    segmentation_vtk_display.OpacityTransferFunction = 'PiecewiseFunction'
    segmentation_vtk_display.DataAxesGrid = 'GridAxesRepresentation'
    segmentation_vtk_display.SelectionCellLabelBold = 0
    segmentation_vtk_display.SelectionCellLabelColor = [0.0, 1.0, 0.0]
    segmentation_vtk_display.SelectionCellLabelFontFamily = 'Arial'
    segmentation_vtk_display.SelectionCellLabelFontFile = ''
    segmentation_vtk_display.SelectionCellLabelFontSize = 18
    segmentation_vtk_display.SelectionCellLabelItalic = 0
    segmentation_vtk_display.SelectionCellLabelJustification = 'Left'
    segmentation_vtk_display.SelectionCellLabelOpacity = 1.0
    segmentation_vtk_display.SelectionCellLabelShadow = 0
    segmentation_vtk_display.SelectionPointLabelBold = 0
    segmentation_vtk_display.SelectionPointLabelColor = [1.0, 1.0, 0.0]
    segmentation_vtk_display.SelectionPointLabelFontFamily = 'Arial'
    segmentation_vtk_display.SelectionPointLabelFontFile = ''
    segmentation_vtk_display.SelectionPointLabelFontSize = 18
    segmentation_vtk_display.SelectionPointLabelItalic = 0
    segmentation_vtk_display.SelectionPointLabelJustification = 'Left'
    segmentation_vtk_display.SelectionPointLabelOpacity = 1.0
    segmentation_vtk_display.SelectionPointLabelShadow = 0
    segmentation_vtk_display.PolarAxes = 'PolarAxesRepresentation'

    # init the 'PiecewiseFunction' selected for 'OSPRayScaleFunction'
    segmentation_vtk_display.OSPRayScaleFunction.Points = [0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0]
    segmentation_vtk_display.OSPRayScaleFunction.UseLogScale = 0

    # init the 'Arrow' selected for 'GlyphType'
    segmentation_vtk_display.GlyphType.TipResolution = 6
    segmentation_vtk_display.GlyphType.TipRadius = 0.1
    segmentation_vtk_display.GlyphType.TipLength = 0.35
    segmentation_vtk_display.GlyphType.ShaftResolution = 6
    segmentation_vtk_display.GlyphType.ShaftRadius = 0.03
    segmentation_vtk_display.GlyphType.Invert = 0

    # init the 'PiecewiseFunction' selected for 'ScaleTransferFunction'
    segmentation_vtk_display.ScaleTransferFunction.Points = [-0.9999579787254333, 0.0, 0.5, 0.0, 0.9999560117721558, 1.0, 0.5, 0.0]
    segmentation_vtk_display.ScaleTransferFunction.UseLogScale = 0

    # init the 'PiecewiseFunction' selected for 'OpacityTransferFunction'
    segmentation_vtk_display.OpacityTransferFunction.Points = [-0.9999579787254333, 0.0, 0.5, 0.0, 0.9999560117721558, 1.0, 0.5, 0.0]
    segmentation_vtk_display.OpacityTransferFunction.UseLogScale = 0

    # init the 'GridAxesRepresentation' selected for 'DataAxesGrid'
    segmentation_vtk_display.DataAxesGrid.XTitle = 'X Axis'
    segmentation_vtk_display.DataAxesGrid.YTitle = 'Y Axis'
    segmentation_vtk_display.DataAxesGrid.ZTitle = 'Z Axis'
    segmentation_vtk_display.DataAxesGrid.XTitleFontFamily = 'Arial'
    segmentation_vtk_display.DataAxesGrid.XTitleFontFile = ''
    segmentation_vtk_display.DataAxesGrid.XTitleBold = 0
    segmentation_vtk_display.DataAxesGrid.XTitleItalic = 0
    segmentation_vtk_display.DataAxesGrid.XTitleFontSize = 12
    segmentation_vtk_display.DataAxesGrid.XTitleShadow = 0
    segmentation_vtk_display.DataAxesGrid.XTitleOpacity = 1.0
    segmentation_vtk_display.DataAxesGrid.YTitleFontFamily = 'Arial'
    segmentation_vtk_display.DataAxesGrid.YTitleFontFile = ''
    segmentation_vtk_display.DataAxesGrid.YTitleBold = 0
    segmentation_vtk_display.DataAxesGrid.YTitleItalic = 0
    segmentation_vtk_display.DataAxesGrid.YTitleFontSize = 12
    segmentation_vtk_display.DataAxesGrid.YTitleShadow = 0
    segmentation_vtk_display.DataAxesGrid.YTitleOpacity = 1.0
    segmentation_vtk_display.DataAxesGrid.ZTitleFontFamily = 'Arial'
    segmentation_vtk_display.DataAxesGrid.ZTitleFontFile = ''
    segmentation_vtk_display.DataAxesGrid.ZTitleBold = 0
    segmentation_vtk_display.DataAxesGrid.ZTitleItalic = 0
    segmentation_vtk_display.DataAxesGrid.ZTitleFontSize = 12
    segmentation_vtk_display.DataAxesGrid.ZTitleShadow = 0
    segmentation_vtk_display.DataAxesGrid.ZTitleOpacity = 1.0
    segmentation_vtk_display.DataAxesGrid.FacesToRender = 63
    segmentation_vtk_display.DataAxesGrid.CullBackface = 0
    segmentation_vtk_display.DataAxesGrid.CullFrontface = 1
    segmentation_vtk_display.DataAxesGrid.ShowGrid = 0
    segmentation_vtk_display.DataAxesGrid.ShowEdges = 1
    segmentation_vtk_display.DataAxesGrid.ShowTicks = 1
    segmentation_vtk_display.DataAxesGrid.LabelUniqueEdgesOnly = 1
    segmentation_vtk_display.DataAxesGrid.AxesToLabel = 63
    segmentation_vtk_display.DataAxesGrid.XLabelFontFamily = 'Arial'
    segmentation_vtk_display.DataAxesGrid.XLabelFontFile = ''
    segmentation_vtk_display.DataAxesGrid.XLabelBold = 0
    segmentation_vtk_display.DataAxesGrid.XLabelItalic = 0
    segmentation_vtk_display.DataAxesGrid.XLabelFontSize = 12
    segmentation_vtk_display.DataAxesGrid.XLabelShadow = 0
    segmentation_vtk_display.DataAxesGrid.XLabelOpacity = 1.0
    segmentation_vtk_display.DataAxesGrid.YLabelFontFamily = 'Arial'
    segmentation_vtk_display.DataAxesGrid.YLabelFontFile = ''
    segmentation_vtk_display.DataAxesGrid.YLabelBold = 0
    segmentation_vtk_display.DataAxesGrid.YLabelItalic = 0
    segmentation_vtk_display.DataAxesGrid.YLabelFontSize = 12
    segmentation_vtk_display.DataAxesGrid.YLabelShadow = 0
    segmentation_vtk_display.DataAxesGrid.YLabelOpacity = 1.0
    segmentation_vtk_display.DataAxesGrid.ZLabelFontFamily = 'Arial'
    segmentation_vtk_display.DataAxesGrid.ZLabelFontFile = ''
    segmentation_vtk_display.DataAxesGrid.ZLabelBold = 0
    segmentation_vtk_display.DataAxesGrid.ZLabelItalic = 0
    segmentation_vtk_display.DataAxesGrid.ZLabelFontSize = 12
    segmentation_vtk_display.DataAxesGrid.ZLabelShadow = 0
    segmentation_vtk_display.DataAxesGrid.ZLabelOpacity = 1.0
    segmentation_vtk_display.DataAxesGrid.XAxisNotation = 'Mixed'
    segmentation_vtk_display.DataAxesGrid.XAxisPrecision = 2
    segmentation_vtk_display.DataAxesGrid.XAxisUseCustomLabels = 0
    segmentation_vtk_display.DataAxesGrid.XAxisLabels = []
    segmentation_vtk_display.DataAxesGrid.YAxisNotation = 'Mixed'
    segmentation_vtk_display.DataAxesGrid.YAxisPrecision = 2
    segmentation_vtk_display.DataAxesGrid.YAxisUseCustomLabels = 0
    segmentation_vtk_display.DataAxesGrid.YAxisLabels = []
    segmentation_vtk_display.DataAxesGrid.ZAxisNotation = 'Mixed'
    segmentation_vtk_display.DataAxesGrid.ZAxisPrecision = 2
    segmentation_vtk_display.DataAxesGrid.ZAxisUseCustomLabels = 0
    segmentation_vtk_display.DataAxesGrid.ZAxisLabels = []
    segmentation_vtk_display.DataAxesGrid.UseCustomBounds = 0
    segmentation_vtk_display.DataAxesGrid.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]

    # init the 'PolarAxesRepresentation' selected for 'PolarAxes'
    segmentation_vtk_display.PolarAxes.Visibility = 0
    segmentation_vtk_display.PolarAxes.Translation = [0.0, 0.0, 0.0]
    segmentation_vtk_display.PolarAxes.Scale = [1.0, 1.0, 1.0]
    segmentation_vtk_display.PolarAxes.Orientation = [0.0, 0.0, 0.0]
    segmentation_vtk_display.PolarAxes.EnableCustomBounds = [0, 0, 0]
    segmentation_vtk_display.PolarAxes.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
    segmentation_vtk_display.PolarAxes.EnableCustomRange = 0
    segmentation_vtk_display.PolarAxes.CustomRange = [0.0, 1.0]
    segmentation_vtk_display.PolarAxes.PolarAxisVisibility = 1
    segmentation_vtk_display.PolarAxes.RadialAxesVisibility = 1
    segmentation_vtk_display.PolarAxes.DrawRadialGridlines = 1
    segmentation_vtk_display.PolarAxes.PolarArcsVisibility = 1
    segmentation_vtk_display.PolarAxes.DrawPolarArcsGridlines = 1
    segmentation_vtk_display.PolarAxes.NumberOfRadialAxes = 0
    segmentation_vtk_display.PolarAxes.AutoSubdividePolarAxis = 1
    segmentation_vtk_display.PolarAxes.NumberOfPolarAxis = 0
    segmentation_vtk_display.PolarAxes.MinimumRadius = 0.0
    segmentation_vtk_display.PolarAxes.MinimumAngle = 0.0
    segmentation_vtk_display.PolarAxes.MaximumAngle = 90.0
    segmentation_vtk_display.PolarAxes.RadialAxesOriginToPolarAxis = 1
    segmentation_vtk_display.PolarAxes.Ratio = 1.0
    segmentation_vtk_display.PolarAxes.PolarAxisColor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.PolarAxes.PolarArcsColor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.PolarAxes.LastRadialAxisColor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.PolarAxes.SecondaryPolarArcsColor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.PolarAxes.SecondaryRadialAxesColor = [1.0, 1.0, 1.0]
    segmentation_vtk_display.PolarAxes.PolarAxisTitleVisibility = 1
    segmentation_vtk_display.PolarAxes.PolarAxisTitle = 'Radial Distance'
    segmentation_vtk_display.PolarAxes.PolarAxisTitleLocation = 'Bottom'
    segmentation_vtk_display.PolarAxes.PolarLabelVisibility = 1
    segmentation_vtk_display.PolarAxes.PolarLabelFormat = '%-#6.3g'
    segmentation_vtk_display.PolarAxes.PolarLabelExponentLocation = 'Labels'
    segmentation_vtk_display.PolarAxes.RadialLabelVisibility = 1
    segmentation_vtk_display.PolarAxes.RadialLabelFormat = '%-#3.1f'
    segmentation_vtk_display.PolarAxes.RadialLabelLocation = 'Bottom'
    segmentation_vtk_display.PolarAxes.RadialUnitsVisibility = 1
    segmentation_vtk_display.PolarAxes.ScreenSize = 10.0
    segmentation_vtk_display.PolarAxes.PolarAxisTitleOpacity = 1.0
    segmentation_vtk_display.PolarAxes.PolarAxisTitleFontFamily = 'Arial'
    segmentation_vtk_display.PolarAxes.PolarAxisTitleFontFile = ''
    segmentation_vtk_display.PolarAxes.PolarAxisTitleBold = 0
    segmentation_vtk_display.PolarAxes.PolarAxisTitleItalic = 0
    segmentation_vtk_display.PolarAxes.PolarAxisTitleShadow = 0
    segmentation_vtk_display.PolarAxes.PolarAxisTitleFontSize = 12
    segmentation_vtk_display.PolarAxes.PolarAxisLabelOpacity = 1.0
    segmentation_vtk_display.PolarAxes.PolarAxisLabelFontFamily = 'Arial'
    segmentation_vtk_display.PolarAxes.PolarAxisLabelFontFile = ''
    segmentation_vtk_display.PolarAxes.PolarAxisLabelBold = 0
    segmentation_vtk_display.PolarAxes.PolarAxisLabelItalic = 0
    segmentation_vtk_display.PolarAxes.PolarAxisLabelShadow = 0
    segmentation_vtk_display.PolarAxes.PolarAxisLabelFontSize = 12
    segmentation_vtk_display.PolarAxes.LastRadialAxisTextOpacity = 1.0
    segmentation_vtk_display.PolarAxes.LastRadialAxisTextFontFamily = 'Arial'
    segmentation_vtk_display.PolarAxes.LastRadialAxisTextFontFile = ''
    segmentation_vtk_display.PolarAxes.LastRadialAxisTextBold = 0
    segmentation_vtk_display.PolarAxes.LastRadialAxisTextItalic = 0
    segmentation_vtk_display.PolarAxes.LastRadialAxisTextShadow = 0
    segmentation_vtk_display.PolarAxes.LastRadialAxisTextFontSize = 12
    segmentation_vtk_display.PolarAxes.SecondaryRadialAxesTextOpacity = 1.0
    segmentation_vtk_display.PolarAxes.SecondaryRadialAxesTextFontFamily = 'Arial'
    segmentation_vtk_display.PolarAxes.SecondaryRadialAxesTextFontFile = ''
    segmentation_vtk_display.PolarAxes.SecondaryRadialAxesTextBold = 0
    segmentation_vtk_display.PolarAxes.SecondaryRadialAxesTextItalic = 0
    segmentation_vtk_display.PolarAxes.SecondaryRadialAxesTextShadow = 0
    segmentation_vtk_display.PolarAxes.SecondaryRadialAxesTextFontSize = 12
    segmentation_vtk_display.PolarAxes.EnableDistanceLOD = 1
    segmentation_vtk_display.PolarAxes.DistanceLODThreshold = 0.7
    segmentation_vtk_display.PolarAxes.EnableViewAngleLOD = 1
    segmentation_vtk_display.PolarAxes.ViewAngleLODThreshold = 0.7
    segmentation_vtk_display.PolarAxes.SmallestVisiblePolarAngle = 0.5
    segmentation_vtk_display.PolarAxes.PolarTicksVisibility = 1
    segmentation_vtk_display.PolarAxes.ArcTicksOriginToPolarAxis = 1
    segmentation_vtk_display.PolarAxes.TickLocation = 'Both'
    segmentation_vtk_display.PolarAxes.AxisTickVisibility = 1
    segmentation_vtk_display.PolarAxes.AxisMinorTickVisibility = 0
    segmentation_vtk_display.PolarAxes.ArcTickVisibility = 1
    segmentation_vtk_display.PolarAxes.ArcMinorTickVisibility = 0
    segmentation_vtk_display.PolarAxes.DeltaAngleMajor = 10.0
    segmentation_vtk_display.PolarAxes.DeltaAngleMinor = 5.0
    segmentation_vtk_display.PolarAxes.PolarAxisMajorTickSize = 0.0
    segmentation_vtk_display.PolarAxes.PolarAxisTickRatioSize = 0.3
    segmentation_vtk_display.PolarAxes.PolarAxisMajorTickThickness = 1.0
    segmentation_vtk_display.PolarAxes.PolarAxisTickRatioThickness = 0.5
    segmentation_vtk_display.PolarAxes.LastRadialAxisMajorTickSize = 0.0
    segmentation_vtk_display.PolarAxes.LastRadialAxisTickRatioSize = 0.3
    segmentation_vtk_display.PolarAxes.LastRadialAxisMajorTickThickness = 1.0
    segmentation_vtk_display.PolarAxes.LastRadialAxisTickRatioThickness = 0.5
    segmentation_vtk_display.PolarAxes.ArcMajorTickSize = 0.0
    segmentation_vtk_display.PolarAxes.ArcTickRatioSize = 0.3
    segmentation_vtk_display.PolarAxes.ArcMajorTickThickness = 1.0
    segmentation_vtk_display.PolarAxes.ArcTickRatioThickness = 0.5
    segmentation_vtk_display.PolarAxes.Use2DMode = 0
    segmentation_vtk_display.PolarAxes.UseLogAxis = 0

    return segmentation_vtk_display