import unittest
import os, shutil
import numpy as np
from arterial.access_prediction.access_predictor import AccessPredictor

class TestAccessPredictor(unittest.TestCase):
    def setUp(self):
        self.case_dir = os.path.join(os.path.dirname(__file__), "test_data")
        self.mode = "extracranial_vessels"
        self.cta_nifti_path = os.path.join(self.case_dir, "input_test_data", "cta.nii.gz")
        self.supersegments_dir_path = os.path.join(self.case_dir, "input_test_data", "supersegments")
        self.access = ["femoral"]
        self.side = ["left", "right"]
        
        # Check if necessary files exist before setup
        if not os.path.exists(self.cta_nifti_path):
            self.skipTest(f"CTA nifti file {self.cta_nifti_path} not found")
            
        # Check if supersegment files exist
        for access in self.access:
            for side in self.side:
                supersegment_path = os.path.join(self.supersegments_dir_path, f"{access} + {side} + anterior.pickle")
                if not os.path.exists(supersegment_path):
                    self.skipTest(f"Supersegment file {supersegment_path} not found")
        
        # Initialize the AccessPredictor
        self.access_predictor = AccessPredictor(
            case_dir=self.case_dir,
            cta_nifti_path=self.cta_nifti_path,
            supersegments_dir_path=self.supersegments_dir_path,
            access=self.access,
            side=self.side
        )

    def test_init(self):
        self.assertEqual(self.access_predictor.case_dir, self.case_dir)
        self.assertEqual(self.access_predictor.cta_nifti_path, self.cta_nifti_path)
        self.assertEqual(self.access_predictor.access, self.access)
        self.assertEqual(self.access_predictor.side, self.side)
        self.assertIsNone(self.access_predictor.cta_nifti)
        self.assertEqual(self.access_predictor.access_prediction_dir_path, 
                        os.path.join(self.case_dir, "extracranial_vessels", "access_prediction"))
        self.assertEqual(self.access_predictor.raw_supersegment_dict, {})
        self.assertEqual(self.access_predictor.preprocessed_supersegment_dict, {})
        self.assertIsNone(self.access_predictor.lpi_corner_coordinates)
        self.assertEqual(self.access_predictor.predictions_dict, {})
        self.assertEqual(self.access_predictor.attention_maps_dict, {})
        self.assertEqual(self.access_predictor.attention_maps_vtk_dict, {})
        self.assertEqual(self.access_predictor.attention_maps_point_dict, {})

    def test_preprocess_supersegments(self):
        # Reset all attibutes that should be generated by the preprocessing
        self.access_predictor.raw_supersegment_dict = {}
        self.access_predictor.preprocessed_supersegment_dict = {}
        # Run the actual preprocessing
        self.access_predictor.preprocess_supersegments(save=True)
        
        # Check results
        for access in self.access:
            for side in self.side:
                # Check that the supersegment was loaded
                self.assertIn((access, side), self.access_predictor.raw_supersegment_dict)
                self.assertIsNotNone(self.access_predictor.raw_supersegment_dict[(access, side)])
                
                # Check that preprocessing was performed
                self.assertIn((access, side), self.access_predictor.preprocessed_supersegment_dict)
                self.assertIn("global_features", self.access_predictor.preprocessed_supersegment_dict[(access, side)])
                self.assertIn("segment_graph", self.access_predictor.preprocessed_supersegment_dict[(access, side)])
                self.assertIn("dense_graph", self.access_predictor.preprocessed_supersegment_dict[(access, side)])
                
                # Check that files were created
                self.assertTrue(os.path.exists(os.path.join(self.access_predictor.access_prediction_dir_path, f"{access}_{side}")))
                self.assertTrue(os.path.exists(os.path.join(self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "global_features.json")))
                self.assertTrue(os.path.exists(os.path.join(self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "segment_supersegment.pickle")))
                self.assertTrue(os.path.exists(os.path.join(self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "dense_supersegment.pickle")))
                self.assertTrue(os.path.exists(os.path.join(self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "preprocessed_supersegment_dict.pickle")))
                self.assertTrue(os.path.exists(os.path.join(self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "combined_plot.png")))


    def test_full_pipeline(self):
        # Reset all attibutes that should be generated by the full pipeline
        self.access_predictor.cta_nifti = None
        self.access_predictor.lpi_corner_coordinates = None
        self.access_predictor.predictions_dict = {}
        self.access_predictor.attention_maps_dict = {}
        self.access_predictor.attention_maps_vtk_dict = {}
        self.access_predictor.attention_maps_point_dict = {}
        # Run the full pipeline: preprocessing + prediction
        self.access_predictor.preprocess_supersegments(save=True)
        self.access_predictor.predict_accessibility(return_attention_map=True, save=True)
        
        # Check results
        for access in self.access:
            for side in self.side:
                # Check predictions were made
                self.assertIn((access, side), self.access_predictor.predictions_dict)
                self.assertIn("mean", self.access_predictor.predictions_dict[(access, side)])
                self.assertIn("std", self.access_predictor.predictions_dict[(access, side)])
                
                # Check attention maps were created
                self.assertIn((access, side), self.access_predictor.attention_maps_dict)
                self.assertIn((access, side), self.access_predictor.attention_maps_vtk_dict)
                self.assertIn((access, side), self.access_predictor.attention_maps_point_dict)
                
                # Check files were created
                self.assertTrue(os.path.exists(os.path.join(
                    self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "access_prediction.json")))
                self.assertTrue(os.path.exists(os.path.join(
                    self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "attention_map.pickle")))
                self.assertTrue(os.path.exists(os.path.join(
                    self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "attention_map.png")))
                self.assertTrue(os.path.exists(os.path.join(
                    self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "attention_map.vtk")))
                self.assertTrue(os.path.exists(os.path.join(
                    self.access_predictor.access_prediction_dir_path, f"{access}_{side}", "attention_map_points.json")))

    def test_compute_lpi_corner_coordinates(self):
        # Reset all attibutes that should be generated by the compute_lpi_corner_coordinates method
        self.access_predictor.cta_nifti = None
        self.access_predictor.lpi_corner_coordinates = None
        # Run the actual LPI corner coordinate computation
        self.access_predictor.compute_lpi_corner_coordinates()
        
        # Check results
        self.assertIsNotNone(self.access_predictor.cta_nifti)
        self.assertIsNotNone(self.access_predictor.lpi_corner_coordinates)
        self.assertEqual(len(self.access_predictor.lpi_corner_coordinates), 3)  # Should be x, y, z coordinates

    def test_load_cta_nifti(self):
        # Reset the cta_nifti attribute
        self.access_predictor.cta_nifti = None
        # Run the actual load_cta_nifti method
        self.access_predictor._load_cta_nifti_from_file()
        
        # Check that the CTA nifti was loaded
        self.assertIsNotNone(self.access_predictor.cta_nifti)
    

    @classmethod
    def tearDownClass(cls):
        # Remove all the files generated during the tests
        cls.case_dir = os.path.join(os.path.dirname(__file__), "test_data")
        for filename in os.listdir(cls.case_dir):
            if filename not in ["input_test_data", "output"]:
                if os.path.isfile(os.path.join(cls.case_dir, filename)):
                    os.remove(os.path.join(cls.case_dir, filename))
                elif os.path.isdir(os.path.join(cls.case_dir, filename)):
                    shutil.rmtree(os.path.join(cls.case_dir, filename))

if __name__ == '__main__':
    unittest.main() 