#    Copyright 2022-2026 Vall d'Hebron Research Institute (VHIR) and Universitat de Barcelona (UB), Barcelona, Spain.
#    SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

"""
Tests on real execution products regenerated by tests/make_derived_fixtures.py.
They cover the paths that need a full run behind them: branch-model
unification, single-segment export to VTK, the carotid geometry analysis,
individual centerline graphs and landmark refinement.
"""

import glob
import os
import shutil

import numpy as np
import nibabel as nib
from vtk.util.numpy_support import vtk_to_numpy

from helpers import ArterialTestCase, fixture, slow
from arterial.io.load_and_save_operations import load_pickle, load_json, load_vtkpolydata
from arterial.centerline_extraction.postprocessing.branch_and_clipped_model_extraction import unify_branch_models
from arterial.feature_extraction.feature_extractor import FeatureExtractor
from arterial.feature_extraction.graph_builder import build_individual_centerline_graph_from_vtkpolydata
from arterial.feature_extraction.utils import centerline_sanity_check
from arterial.feature_extraction.global_features import utils as global_utils
from arterial.feature_extraction.segment_features.utils import plot_single_segments
from arterial.landmark_detection.utils import refine_landmarks_with_segmentation

DERIVED = fixture("derived", "extracranial_vessels")


class ProductsTestCase(ArterialTestCase):
    """Copies the derived products into the temporary case directory."""

    def setUp(self):
        super().setUp()
        if not os.path.isdir(DERIVED):
            self.skipTest("derived fixtures missing; run tests/make_derived_fixtures.py")
        shutil.copytree(DERIVED, self.mode_dir)
        self.cta_nifti_path = self.require_fixture("cta.nii.gz")

    def product(self, *parts):
        return os.path.join(self.mode_dir, *parts)

    def feature_extractor(self):
        return FeatureExtractor(self.case_dir, self.mode, 2, self.cta_nifti_path, self.product("centerline_segments_array.npy"),
                                self.product("branch_model.vtk"), self.product("segments_graph_pred.pickle"))


class TestBranchModels(ProductsTestCase):

    def test_unify_several_branch_models(self):
        paths = sorted(glob.glob(self.product("branch_models", "branch_model_*.vtk")))
        self.assertGreaterEqual(len(paths), 2, "the fixture case should yield several islands")
        models = [load_vtkpolydata(p) for p in paths]
        unified = unify_branch_models(models, radius_array_name="MaximumInscribedSphereRadius")
        self.assertEqual(unified.GetNumberOfPoints(), sum(m.GetNumberOfPoints() for m in models))
        self.assertEqual(unified.GetNumberOfCells(), sum(m.GetNumberOfCells() for m in models))
        self.assertIsNotNone(unified.GetCellData().GetArray("Blanking"))
        with self.assertRaises(ValueError):
            unify_branch_models([])


class TestGlobalFeaturesOnRealGraph(ProductsTestCase):

    def test_global_features_have_valid_values(self):
        local_graph = load_pickle(self.product("local_graph.pickle"))
        self.assertIn(global_utils.get_aortic_arch_type(local_graph), (1, 2, 3))
        self.assertIn(global_utils.get_bovine_arch(local_graph), (0, 1))
        self.assertIn(global_utils.get_arsa(local_graph), (0, 1))
        self.assertIn("aortic_arch_type", local_graph.graph)

    def test_single_segment_plot_with_two_vessel_types(self):
        local_graph = load_pickle(self.product("local_graph.pickle"))
        segments = {name: load_pickle(self.product("single_segments", f"{name}.pickle")) for name in ["LCCA", "LICA"]}
        output = os.path.join(self.case_dir, "two_types.png")
        plot_single_segments(local_graph, segments, output_path=output)
        self.assertFileExists(output)


class TestVesselGeometryExport(ProductsTestCase):

    def test_single_segment_to_vtk_and_geometry(self):
        extractor = self.feature_extractor()
        graph = load_pickle(self.product("single_segments", "LICA.pickle"))
        centerline = extractor.single_segment_pickle_to_vtk(graph)
        n = centerline.GetNumberOfPoints()
        self.assertEqual(n, graph.number_of_nodes())
        for name in ["Tangents", "Normals", "Binormals", "Blanking", "VesselType"]:
            self.assertIsNotNone(centerline.GetPointData().GetArray(name), name)
        self.assertIsNotNone(centerline.GetPointData().GetAbstractArray("VesselTypeName"))
        surface = load_vtkpolydata(self.product("segmentation.vtk"))
        out = extractor.add_centerline_geometry(centerline, surface_model=surface, compute_curves=True, savgol_window_length=11)
        for name in ["Radius CE", "Radius CC", "Ovality", "Curvature", "Torsion", "Filtered curvature", "Distance from origin", "CurveIds"]:
            self.assertEqual(out.GetPointData().GetArray(name).GetNumberOfTuples(), n, name)
        radius_ce = vtk_to_numpy(out.GetPointData().GetArray("Radius CE"))
        self.assertTrue(np.all(np.isfinite(radius_ce)))
        self.assertTrue(np.all((radius_ce > 0.3) & (radius_ce < 10.0)), f"implausible ICA radii: {radius_ce.min()} .. {radius_ce.max()}")
        distance = vtk_to_numpy(out.GetPointData().GetArray("Distance from origin"))
        self.assertTrue(np.all(np.diff(distance) >= 0))

    def test_carotid_analysis_with_and_without_landmark(self):
        extractor = self.feature_extractor()
        graph = load_pickle(self.product("single_segments", "LCA.pickle"))
        centerline = extractor.add_centerline_geometry(extractor.single_segment_pickle_to_vtk(graph), surface_model=load_vtkpolydata(self.product("segmentation.vtk")))
        n = centerline.GetNumberOfPoints()
        for use_landmark in (False, True):
            with self.subTest(use_landmark=use_landmark):
                out = extractor.add_carotid_analysis(centerline, side="LCA", use_landmark=use_landmark)
                for name in ["BulbMask", "BifurcationMask", "KeepAfterBlankingTrim"]:
                    self.assertEqual(out.GetPointData().GetArray(name).GetNumberOfTuples(), n, name)
                bulb = vtk_to_numpy(out.GetPointData().GetArray("BulbMask"))
                self.assertTrue(set(np.unique(bulb).tolist()) <= {0, 1})
        landmark = extractor._resolve_bulb_landmark("LCA")
        self.assertIsNotNone(landmark)
        self.assertEqual(len(landmark), 3)
        with self.assertRaises(ValueError):
            extractor._resolve_bulb_landmark("XYZ")

    @slow
    def test_intracranial_transition_on_the_cta(self):
        extractor = self.feature_extractor()
        graph = load_pickle(self.product("single_segments", "LICA.pickle"))
        centerline = extractor.single_segment_pickle_to_vtk(graph)
        out = extractor.add_intracranial_transition(centerline)
        intracranial = vtk_to_numpy(out.GetPointData().GetArray("Intracranial"))
        self.assertEqual(len(intracranial), centerline.GetNumberOfPoints())
        self.assertTrue(set(np.unique(intracranial).tolist()) <= {0, 1})


class TestIndividualCenterlines(ProductsTestCase):

    def test_graph_from_individual_centerline(self):
        cta = nib.load(self.cta_nifti_path)
        model = load_vtkpolydata(self.product("individual_centerlines", "individual_centerline_l-ica.vtk"))
        self.assertGreater(model.GetNumberOfPoints(), 0)
        graph = build_individual_centerline_graph_from_vtkpolydata(model, cta.affine, cta.shape, sampling_distance_mm=2.0, centerline_id="l-ica")
        self.assertGreater(graph.number_of_nodes(), 5)
        self.assertEqual(graph.number_of_edges(), graph.number_of_nodes() - 1, "an individual centerline is a chain")
        self.assertIn("pos", graph.nodes[next(iter(graph))])
        self.assertIsInstance(centerline_sanity_check(model, np.asarray(cta.dataobj), cta.affine), (bool, np.bool_))

    @slow
    def test_featurize_individual_centerline(self):
        extractor = self.feature_extractor()
        model = load_vtkpolydata(self.product("individual_centerlines", "individual_centerline_r-ica.vtk"))
        extractor.build_and_featurize_individual_centerline_graph(model, centerline_id="r-ica", save=True)
        self.assertFileExists(self.product("individual_centerlines", "individual_centerline_r-ica.pickle"))


class TestLandmarkRefinement(ProductsTestCase):

    @slow
    def test_refinement_keeps_labels_and_moves_points_only_slightly(self):
        landmarks = load_json(self.product("landmarks.json"))
        segmentation = nib.load(self.require_fixture("segmentation.nii.gz"))
        refined, stats = refine_landmarks_with_segmentation(landmarks, np.asarray(segmentation.dataobj), segmentation.affine, search_radius_mm=5.0)
        self.assertEqual(set(refined), set(landmarks))
        for name in landmarks:
            displacement = np.linalg.norm(np.asarray(refined[name], float) - np.asarray(landmarks[name], float))
            self.assertLessEqual(displacement, 5.0 + 1e-6, f"{name} moved {displacement:.1f} mm")
        self.assertIsInstance(stats, dict)
