#    Copyright 2022-2026 Vall d'Hebron Research Institute (VHIR) and Universitat de Barcelona (UB), Barcelona, Spain.
#    SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

"""
Small helpers shared by the notebooks: where the data is, and a few plots.
"""

import os
import time
from contextlib import contextmanager

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from vtk.util.numpy_support import vtk_to_numpy

NOTEBOOKS_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(NOTEBOOKS_DIR)
FIXTURES_DIR = os.path.join(REPO_ROOT, "tests", "test_data", "input_test_data")
DERIVED_DIR = os.path.join(FIXTURES_DIR, "derived", "extracranial_vessels")
CASE_DIR = os.path.join(NOTEBOOKS_DIR, "case")   # everything the notebooks write goes here (gitignored)
MODE = "extracranial_vessels"

os.environ.setdefault("arterial_dir", os.path.join(REPO_ROOT, "arterial"))
os.makedirs(CASE_DIR, exist_ok=True)


INLINE_BACKEND = "module://matplotlib_inline.backend_inline"


def _keep_inline_plots():
    """
    nnU-Net switches matplotlib to the non-interactive Agg backend the first
    time it loads a checkpoint, which silently stops figures from showing in a
    notebook. Restore the inline backend before every cell.

    """
    try:
        from IPython import get_ipython
        shell = get_ipython()
        if shell is None:
            return
        shell.events.register("pre_run_cell", lambda *args: matplotlib.use(INLINE_BACKEND, force=True))
    except Exception:
        pass


def show(fig):
    """
    Displays a figure even if a library switched the backend during the cell.

    """
    if matplotlib.get_backend() != INLINE_BACKEND:
        try:
            from IPython.display import display
            display(fig)
            plt.close(fig)
        except Exception:
            pass
    return fig


_keep_inline_plots()


def fixture(*parts):
    """
    Path to an input fixture; raises a readable error if the test data is missing.

    """
    path = os.path.join(FIXTURES_DIR, *parts)
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} is missing. The notebooks use the test fixtures; see tests/README.md.")
    return path


def derived(*parts):
    """
    Path to a product of an earlier stage, regenerated by tests/make_derived_fixtures.py.

    """
    path = os.path.join(DERIVED_DIR, *parts)
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} is missing. Run `python tests/make_derived_fixtures.py` first.")
    return path


def case(*parts):
    """
    Path inside the notebooks' working case directory.

    """
    return os.path.join(CASE_DIR, *parts)


@contextmanager
def quiet():
    """
    Silences the console output of a block (nnU-Net and VMTK print a lot).

    """
    import io
    from contextlib import redirect_stdout, redirect_stderr
    sink = io.StringIO()
    with redirect_stdout(sink), redirect_stderr(sink):
        yield


@contextmanager
def timed(label):
    """
    Prints how long a block took.

    """
    start = time.time()
    yield
    print(f"{label}: {time.time() - start:.1f} s")


def table(rows, columns=None, index=None):
    """
    Builds a DataFrame for display.

    """
    return pd.DataFrame(rows, columns=columns, index=index)


def show_slices(volume, affine=None, mask=None, indices=None, window=None, title=None, figsize=(15, 5)):
    """
    Shows the sagittal, coronal and axial middle slices of a volume with the
    voxel aspect ratio taken from the affine, and an optional mask overlay.

    """
    volume = np.asarray(volume)
    spacing = np.abs(np.diag(affine)[:3]) if affine is not None else np.ones(3)
    if indices is None:
        indices = [s // 2 for s in volume.shape]
    if window is None:
        window = (np.percentile(volume, 1), np.percentile(volume, 99))
    mask = None if mask is None else np.asarray(mask)
    fig, axes = plt.subplots(1, 3, figsize=figsize)
    # each plane is drawn transposed: rows are the second listed axis, columns the first
    planes = [("sagittal", volume[indices[0], :, :], None if mask is None else mask[indices[0], :, :], spacing[2] / spacing[1]),
              ("coronal", volume[:, indices[1], :], None if mask is None else mask[:, indices[1], :], spacing[2] / spacing[0]),
              ("axial", volume[:, :, indices[2]], None if mask is None else mask[:, :, indices[2]], spacing[1] / spacing[0])]
    for ax, (name, image, overlay, aspect) in zip(axes, planes):
        ax.imshow(image.T, cmap="gray", origin="lower", vmin=window[0], vmax=window[1], aspect=aspect)
        if overlay is not None:
            ax.imshow(np.ma.masked_where(overlay.T == 0, overlay.T), cmap="autumn", origin="lower", alpha=0.6, interpolation="nearest", aspect=aspect)
        ax.set_title(name)
        ax.axis("off")
    if title:
        fig.suptitle(title)
    plt.tight_layout()
    return show(fig)


def plane_aspect(affine, plane):
    """
    Returns the imshow aspect for a transposed slice: 'sagittal' (A vs S), 'coronal' (R vs S) or 'axial' (R vs A).

    """
    spacing = np.abs(np.diag(affine)[:3])
    return {"sagittal": spacing[2] / spacing[1], "coronal": spacing[2] / spacing[0], "axial": spacing[1] / spacing[0]}[plane]


def polydata_lines(polydata):
    """
    Returns the polyline cells of a vtkPolyData as a list of (n, 3) arrays.

    """
    points = vtk_to_numpy(polydata.GetPoints().GetData())
    lines = []
    for c in range(polydata.GetNumberOfCells()):
        ids = polydata.GetCell(c).GetPointIds()
        lines.append(points[[ids.GetId(i) for i in range(ids.GetNumberOfIds())]])
    return lines


def plot_surface(polydata, ax, color="lightgray", alpha=0.35, max_triangles=30000, label=None):
    """
    Draws a triangle surface as a mesh, decimated if it has more than max_triangles faces.

    """
    import vtk
    triangles = vtk.vtkTriangleFilter(); triangles.SetInputData(polydata); triangles.Update()
    surface = triangles.GetOutput()
    if surface.GetNumberOfCells() > max_triangles:
        decimate = vtk.vtkQuadricDecimation(); decimate.SetInputData(surface)
        decimate.SetTargetReduction(1 - max_triangles / surface.GetNumberOfCells()); decimate.Update()
        surface = decimate.GetOutput()
    points = vtk_to_numpy(surface.GetPoints().GetData())
    faces = vtk_to_numpy(surface.GetPolys().GetData()).reshape(-1, 4)[:, 1:]
    ax.plot_trisurf(points[:, 0], points[:, 1], points[:, 2], triangles=faces, color=color, alpha=alpha, linewidth=0, antialiased=False, shade=True, label=label)
    return ax


def plot_polydata(polydatas, colors=None, labels=None, ax=None, surface_step=25, elev=10, azim=-60, title=None, linewidth=1.0):
    """
    Draws centerline polydata as 3D lines and surfaces as meshes.

    """
    if ax is None:
        fig = plt.figure(figsize=(8, 9))
        ax = fig.add_subplot(111, projection="3d")
    colors = colors or [f"C{i}" for i in range(len(polydatas))]
    labels = labels or [None] * len(polydatas)
    for polydata, color, label in zip(polydatas, colors, labels):
        if polydata.GetNumberOfLines() > 0:
            for idx, line in enumerate(polydata_lines(polydata)):
                ax.plot(line[:, 0], line[:, 1], line[:, 2], color=color, linewidth=linewidth, label=label if idx == 0 else None)
        elif polydata.GetNumberOfPolys() > 0:
            plot_surface(polydata, ax, color=color)
        else:
            pts = vtk_to_numpy(polydata.GetPoints().GetData())[::surface_step]
            ax.scatter(pts[:, 0], pts[:, 1], pts[:, 2], s=1, color=color, alpha=0.15, label=label)
    ax.set_xlabel("R"); ax.set_ylabel("A"); ax.set_zlabel("S")
    ax.view_init(elev=elev, azim=azim)
    if any(labels):
        ax.legend(loc="upper left")
    if title:
        ax.set_title(title)
    return ax


def plot_graph(graph, color_by=None, ax=None, cmap="tab20", node_size=6, elev=10, azim=-60, title=None):
    """
    Draws a networkx graph whose nodes carry 'pos', coloured by a node attribute or a function.

    """
    if ax is None:
        fig = plt.figure(figsize=(8, 9))
        ax = fig.add_subplot(111, projection="3d")
    pos = np.array([graph.nodes[n]["pos"] for n in graph])
    for src, dst in graph.edges:
        a, b = graph.nodes[src]["pos"], graph.nodes[dst]["pos"]
        ax.plot([a[0], b[0]], [a[1], b[1]], [a[2], b[2]], color="lightgray", linewidth=0.6)
    if color_by is None:
        values = None
    elif callable(color_by):
        values = [color_by(graph.nodes[n]) for n in graph]
    else:
        values = [graph.nodes[n].get(color_by) for n in graph]
    if values is not None and isinstance(values[0], str):
        names = sorted(set(values)); lookup = {name: i for i, name in enumerate(names)}
        scatter = ax.scatter(pos[:, 0], pos[:, 1], pos[:, 2], c=[lookup[v] for v in values], cmap=cmap, s=node_size)
        handles = [plt.Line2D([], [], marker="o", linestyle="", color=plt.get_cmap(cmap)(lookup[n] / max(1, len(names) - 1)), label=n) for n in names]
        ax.legend(handles=handles, loc="upper left", fontsize=7)
    elif values is not None:
        scatter = ax.scatter(pos[:, 0], pos[:, 1], pos[:, 2], c=values, cmap="viridis", s=node_size)
        plt.colorbar(scatter, ax=ax, shrink=0.6, label=color_by if isinstance(color_by, str) else None)
    else:
        ax.scatter(pos[:, 0], pos[:, 1], pos[:, 2], s=node_size, color="C0")
    ax.set_xlabel("R"); ax.set_ylabel("A"); ax.set_zlabel("S")
    ax.view_init(elev=elev, azim=azim)
    if title:
        ax.set_title(title)
    return ax
